baseURL = 'http://corp.csxl.dev/'
languageCode = 'en-us'
title = 'CSX Labs Corporate'
theme = 'csxlabs-corporate'

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    pre = "pen-tool"
    url = "/articles/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3